### ISSUE TITLE
What the use of "cleandb" in ingest ?

### ISSUE THREAD

**Issue by hippalectryon-0** [su77ungr/CASALIOY#42]
`ingest.py` calls `Qdrant.from_documents`, which itself calls `client.recreate_collection`, which "Delete and create empty collection with given parameters", therefore whatever we set for `cleandb` ("y" or "n"), the db is recreated...

From https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/qdrant.html: "Both Qdrant.from_texts and Qdrant.from_documents methods are great to start using Qdrant with LangChain, but they are going to destroy the collection and create it from scratch! If you want to reuse the existing collection, you can always create an instance of Qdrant on your own and pass the QdrantClient instance with the connection details."

**Comment by su77ungr** [comment]
Jap it is redundant at the current stage of this repo. It was used to overrun a currupted database since it reinitializes within the subtree. 

Documentation was weird at that time [see](https://web.archive.org/web/20230412232007/https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/qdrant.html#on-disk-storage)

Since we are still prototyping we just append it.
