### ISSUE TITLE
Stance towards original repo

### ISSUE THREAD

**Issue by hippalectryon-0** [su77ungr/CASALIOY#62]
This was originally a fork of https://github.com/imartinez/privateGPT/. However the development speed on the main repo is very slow, and we're way ahead now.

In itself that's not an issue; even if they pick up the pace on privateGPT, they may go into another direction.
What's bothering me is the huge amount of issues and PRs opened over there and left hanging, most of which are already solved here.

I really don't know what the right thing to do is - I'm not a pro of Github etiquette at all, but I guess that going over there and telling the issue openers "hey actually it's already fixed in our version" without prior authorisation from @imartinez isn't a great idea. Also, our repo has diverged a tad too much to be able to just merge it into privateGPT.

What do you think ?

**Comment by su77ungr** [comment]
This has been in my mind too lately. In the beginning I was hopping onto their issues to add some support but it seems like he wants to keep a simple boilerplate to offer a quick demo. 

It's just a prototype to get you started and less akin to our toolkit approach. We could ask to request a mention of our page for an more embedded approach, where most issues have been fixed also. 

Other than simplicity there's no real reason to use privateGPT due to it's lower compatibility and performance.

**Comment by su77ungr** [comment]
Let's craft an PR and I'm gonna ping the original repo to add us inside their README

**Comment by su77ungr** [comment]
Gonna do this tomorrow. Everyone feel free to add to this conversation.

**Comment by alxspiker** [comment]
I was doing some PRs over there but seemed like I was going to end up doing all the work. Going my own way as everyone kind of seems slow. https://github.com/alxspiker/AI-X

Planning to use your console script instead of my own so I can focus on the database and UI part of the development. Going to use my own at this moment as its already purposed towards what I need right now.

Its not actually in a working state right this second but I am planning to have it useable tonight. I just started working on the API so the python script can poll the web server to see if it needs to do anything. I am probably an hour or two away from having the chat working on a que system and streaming to the database so the users can see their message as its written.

Using a PHP server allows me to bypass a lot of the restrictions and dependencies python requires and speeds up development heavily for me.

**Comment by atxcowboy** [comment]
@alxspiker I can relate to your preference of PHP over Python. Personally, I've started my journey with a PHP-based open-source project over 20 years (PostNuke CMS), and PHP remains my language of choice. I completely understand the benefits of using PHP over PY with the dependencies. ;)

I'm really impressed by your progress so far and the whole current explosion of open source AI solutions reminds me of the time when I started! 

I own a small hosting business and if you're interested, I'd be happy to donate any resources you may need for the public facing side of your projects. If you're interested, just drop me an email at hello@panomity.com or contact me on Wire messenger at [@atxcowboy](https://account.wire.com/user-profile/?id=5FA786FC-975F-4A72-AA7E-9FE327B8F4D0).

**Comment by hippalectryon-0** [comment]
Keep us updated when the issue is up :)

**Comment by su77ungr** [comment]
https://github.com/imartinez/privateGPT/issues/303

**Comment by su77ungr** [comment]
He's a masochist: 
https://github.com/imartinez/privateGPT/pull/305

I'll close this for now. Maybe on my spare time writing a bot that repsonds to the issues over there.
